### ISSUE TITLE
遇到一个问题希望下次迭代能解决下

### ISSUE THREAD

**Issue by LiAoRJ** [pingc0y/URLFinder#10]
遇到一个ip下存在不同端口对应的Web系统
我利用扫描js的时候，每次扫描不同端口的Web系统所得的结果会将上次的结果所覆盖。
例如 扫描 http://192.168.1.128:8888  所得结果->192.168.1.128.csv
但是我下一次扫描 http://192.168.1.128:9999 所得结果-> 192.168.1.128.csv  这次所得结果将会覆盖上次的结果。
希望下次迭代能够修改。谢谢！

**Comment by pingc0y** [comment]
感谢反馈，下个版本解决该问题

**Comment by pingc0y** [comment]
已更新
