### ISSUE TITLE
bad case report

### ISSUE THREAD

**Issue by ur10ser** [pingc0y/URLFinder#11]
01.baidu.com => get 0 url

Start Spider URL: https://01.baidu.com/
Spider OK
Start Validate...
Validate OK
0 JS to baidu.com

0 JS to other

0 URL to baidu.com

**Comment by ur10ser** [comment]
简单看了下是因为缺失请求头“Accept: */*”导致抓不到正常页面，建议将header参数作为yaml可配置化

**Comment by ur10ser** [comment]
简单看了下是因为缺失请求头“Accept: \*/\*”导致抓不到正常页面，建议将header参数作为yaml可配置化

**Comment by pingc0y** [comment]
感谢反馈，后续更新添加更多可选配置
