### ISSUE TITLE
在mac上貌似无法生存config.yaml文件

### ISSUE THREAD

**Issue by ifacker** [pingc0y/URLFinder#12]
<img width="858" alt="image" src="https://user-images.githubusercontent.com/26481367/189256609-342eda2a-64e9-4fb5-9eb3-edd22843d3c9.png">
本地没有 config 文件貌似不一定会报这个错，所以导致本地没有生成 config 文件，直接就切到“配置文件错误，尝试重新生成了”，还有就是生成的文件我觉得0644的权限更合适（个人意见，权限最小化原则）

**Comment by pingc0y** [comment]
我这边没有mac环境，你能提供下报错信息给我吗？权限问题我很赞同，后续版本会改为0644

**Comment by pingc0y** [comment]
已更新
