### ISSUE TITLE
缺少#

### ISSUE THREAD

**Issue by liutufang** [pingc0y/URLFinder#13]
https://82.156.22.86/#/  扫描时，会出来    https://82.156.22.86/menu                   [status: 404, size: 178, title: 404 Not Found]

但是https://](https://82.156.22.86/#/menu  ,加上#号后就可以访问了。扫描后能不能也判断一下有#号的链接

这个问题可以处理么

**Comment by pingc0y** [comment]
感谢反馈，该问题下次更新会解决

**Comment by pingc0y** [comment]
已更新
