### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by m0s30** [pingc0y/URLFinder#15]
希望可以增加一个参数用于指定爬取某个域名的信息
例如-domain xxx.com
因为爬取发现大量无用url有点耗费资源

**Comment by pingc0y** [comment]
感谢师傅的建议，会考虑下次更新添加该功能。
师傅可以给它起一个参数名呢

**Comment by m0s30** [comment]
还有一个建议，就是爬取的url是否可以记录爬取来源，因为爬取结果有一些没有域名的url，不清楚资产归属也不好测试。不知道是否可以记录url是从哪个页面爬取到的呢？

此外，上述说到的参数名起个：-d

**Comment by pingc0y** [comment]
> 还有一个建议，是否可以记录抓取的url，因为抓取有一些没有域名的url，就是获取资产的获取结果也不知道。的呢？
> 
> 另外，上述证券的参数名起个：-d

该功能我有考虑过，但没想好如何展示才不影响观感，如果一团乱的话有点费眼呢
如果我没有好的展示形式，可能会只有导出到文件才有该记录

**Comment by pingc0y** [comment]
已更新，只有-o 导出才会有抓取来源记录

**Comment by m0s30** [comment]
太效率了师傅，感谢！
