### ISSUE TITLE
结果保存问题

### ISSUE THREAD

**Issue by fucksrc** [pingc0y/URLFinder#16]
师傅好，我看了下如果从url.txt中获取结果，保存的文件是每个url一个  这样子感觉没必要吧  可以都汇总到一个txt中呢

**Comment by fucksrc** [comment]
懂了  直接  cat *.csv > 1.csv    打扰了师傅

**Comment by pingc0y** [comment]
单独到url是方便查看呢，有合并需求就跟师傅操作的一样 cat *.csv > 1.csv 就好了
