### ISSUE TITLE
win10报错

### ISSUE THREAD

**Issue by zglaozhu** [pingc0y/URLFinder#19]
![image](https://user-images.githubusercontent.com/31888299/190494490-ac421a04-94cc-4b3b-8009-1a9dd22d5e56.png)
win10使用最新版本x64  会出现这个
使用的命令
URLFinder.exe -s 200 -m 2 -f url.txt -o C:\Users\admin\Downloads

**Comment by pingc0y** [comment]
感谢反馈，麻烦师傅提供下报错的url，我这边复现不了。

**Comment by zglaozhu** [comment]
https://cdn-huzhu.qschou.com

![image](https://user-images.githubusercontent.com/31888299/190556953-1f513a86-9607-4f30-a285-2048fd7b9657.png)

**Comment by pingc0y** [comment]
已更新，师傅测试下是否正常

**Comment by zglaozhu** [comment]
正常了 谢谢啊
