### ISSUE TITLE
没效果

### ISSUE THREAD

**Issue by MoXiaoJian** [pingc0y/URLFinder#2]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/23404508/173216122-ef7604c7-67d7-4e87-b123-f899a2c75753.png">

**Comment by pingc0y** [comment]
大意了，我把baidu，google等加入黑名单了不会爬取，因为我测试很多站点都会调用baidu的JS这些，没什么用的链接，我就给过滤掉了，后面加回来。

**Comment by MoXiaoJian** [comment]
其他也是这样阿好哥哥![image](https://user-images.githubusercontent.com/23404508/173269660-08cf07dc-86e9-472a-8bc7-803593056dd2.png)

**Comment by pingc0y** [comment]
更新了，缩小了黑名单范围，目前新版本不抓取的名单：github.com,www.w3.org,example.com
试试新版呢

**Comment by pingc0y** [comment]
> 其他也是这样阿好哥哥![image](https://user-images.githubusercontent.com/23404508/173269660-08cf07dc-86e9-472a-8bc7-803593056dd2.png)

更新了,缩小了黑名单范围,目前新版本不抓取的名单:github.com，www.w3.org，example.com
试试新版呢

**Comment by pingc0y** [comment]
> 还是没效果<img alt="image" width="749" src="https://user-images.githubusercontent.com/23404508/173395100-5643982f-8e75-483f-8b21-e571d1524e59.png">

http://www.baidu.com/这个可以，我调试了下，还有一些过滤规则把特定情况下的返回结果过滤了，百度也有点怪，https返回的是一个重定向到http的页面，我已经针对这种情况做了调整。感谢你的反馈，我个人测试遇到的情况较少。
