### ISSUE TITLE
师傅，输出可以提供json格式嘛

### ISSUE THREAD

**Issue by R1ck415** [pingc0y/URLFinder#20]

**Comment by pingc0y** [comment]
网上有一些CSV转JSON的在线工具，师傅可以转换后根据需求改下使用呢
比如：http://www.esjson.com/exceltojson.html  ，  http://www.ab173.com/json/col2json.php

**Comment by R1ck415** [comment]
在尝试集成在其他工具上，csv文件太多好像不太自动化

**Comment by pingc0y** [comment]
建议师傅根据需求修改下代码，更贴合集成呢。我代码写的比较白话，是比较好修改的。
