### ISSUE TITLE
bad case report

### ISSUE THREAD

**Issue by ur10ser** [pingc0y/URLFinder#21]
参考：https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

当a.com的html页面中有base标签时，

如
```
<base href="https://static.cos.com/xxx/"></base>
<script src="js/api.js"></script>
```

应该获取[https://static.cos.com/xxx/js/api.js](https://static.cos.com/xxx/js/api.js)爬取接口，但工具不会识别base标签，最终爬[a.com/js/api.js](a.com/js/api.js)导致404

**Comment by pingc0y** [comment]
感谢反馈，下次更新将会处理该问题。

**Comment by pingc0y** [comment]
已更新
