### ISSUE TITLE
win11 win10均无法运行

### ISSUE THREAD

**Issue by huaiyi255** [pingc0y/URLFinder#22]

**Comment by pingc0y** [comment]
我这边无法复现该问题，师傅是自己编译的吗，还是下载的成品

**Comment by huaiyi255** [comment]
> 我这边无法复现该问题，师傅是自己编译的吗，还是下载的成品

未编译，直接下载的成品，会不会是因为win版本问题？例如专业版，教育版企业版等等而导致不兼容

当前win10版本
![image](https://user-images.githubusercontent.com/52989379/191640094-58981bc0-76af-480c-afad-ab26004c3375.png)

当前win11版本
![Uploading image.png…]()

**Comment by pingc0y** [comment]
师傅测试下这个能不能运行
[URLFinder-windows64.zip](https://github.com/pingc0y/URLFinder/files/9622061/URLFinder-windows64.zip)

**Comment by huaiyi255** [comment]
> 师傅测试下这个能不能运行 [URLFinder-windows64.zip](https://github.com/pingc0y/URLFinder/files/9622061/URLFinder-windows64.zip)

win11 win10都没问题，用起来很棒！

**Comment by pingc0y** [comment]
> > 师傅测试下这个不能运行[URLFinder-windows64.zip](https://github.com/pingc0y/URLFinder/files/9622061/URLFinder-windows64.zip)
> 
> win11 win10没有问题，用起来很了不起！

那就好，请下载新版本使用呢，我这里发的是测试用 有bug的哦

**Comment by huaiyi255** [comment]
> > > 师傅测试下这个不能运行[URLFinder-windows64.zip](https://github.com/pingc0y/URLFinder/files/9622061/URLFinder-windows64.zip)
> > 
> > 
> > win11 win10没有问题，用起来很了不起！
> 
> 那就好，请下载新版本使用呢，我这里发的是测试用 有bug的哦

ok谢谢
