### ISSUE TITLE
可以加个代理

### ISSUE THREAD

**Issue by D1sAbl4** [pingc0y/URLFinder#24]
## 简单添加了HTTP代理带功能
![image](https://user-images.githubusercontent.com/51101413/192723042-1718e8aa-4a09-430d-91ca-d14ea46040ba.png)
---
### 在spider, jsState, urlState三个函数中添加如下代码
![image](https://user-images.githubusercontent.com/51101413/192723572-f72025c1-22ca-4ddd-a5ba-be313996754a.png)
---
### 效果如下
![image](https://user-images.githubusercontent.com/51101413/192724475-b7be46e3-9867-47a8-8db3-820264e92149.png)

**完整代码**: https://gist.github.com/D1sAbl4/f9f55dd619902c0c79d55cbb8d7bc34a

**Comment by pingc0y** [comment]
师傅可以把需要身份证验证的代理也完善进去，发起个 pull requests，加入 Contributors  (๑•̀ㅂ•́)و✧

**Comment by D1sAbl4** [comment]
这个工具确实好用, 这点代码我感觉我不配加入Contributors, 主要我懒, 还有我就是个Java web小开发每天都在忙于搬砖(**996**)

**Comment by pingc0y** [comment]
感谢师傅的代码，那就让我（摸鱼怪）来完善它
