### ISSUE TITLE
请问输出结果是否可以不覆盖？

### ISSUE THREAD

**Issue by zglaozhu** [pingc0y/URLFinder#27]
比如url.txt里面有https://github.com/1  和https://github.com/2  2个url
输出结果只会有1个  是否可以不要覆盖  结果为2个

**Comment by pingc0y** [comment]
下次更新处理这个问题。
师傅，你觉得结果为两个，还是结果合并为一个(不是覆盖)，哪个好些。

**Comment by zglaozhu** [comment]
结果为2个 每个url都有一个结果比较好
或者可以通过参数 自己选择结果为几个 是否覆盖

**Comment by pingc0y** [comment]
那导出的文件名改为完整的url，这样就不会重复覆盖了，也好认些。

**Comment by pingc0y** [comment]
因为:与/都是windows中的命名黑名单，最终以(1),(2)这种方式来对多个结果处理
新版本已经修改

**Comment by zglaozhu** [comment]
好的 我试试
