### ISSUE TITLE
跑出来的路径似乎不会拼接在当前目录

### ISSUE THREAD

**Issue by mrknow001** [pingc0y/URLFinder#28]
跑出来的路径直接拼接在根目录的，没有从当前路径后面增加，或者fuzz，从根目录往后面路径递归测试
![图片](https://user-images.githubusercontent.com/46807619/195040894-d334a197-2927-414c-b8c3-b1aadf80cdf4.png)

**Comment by pingc0y** [comment]
是会在当前路径后面增加的，但不会fuzz。
如果师傅你跑出来的结果不对，可以发链接给我看看。

**Comment by pingc0y** [comment]
拼接是有规则的，/xx/aa.html 这种会拼接到根目录后面，xx/aa.html这种会拼接到当前目录后面，是符合web路径规则的

**Comment by mrknow001** [comment]
可以加上fuzz，每个目录迭代查询下，最近遇到好几次这种了，直接拼接试404，删除两个目录就可以了，而且里面还发现了好东西

**Comment by pingc0y** [comment]
会考虑添加该功能，对404链接进行fuzz

**Comment by pingc0y** [comment]
新版本添加了对目录的fuzz功能，师傅可以对之前遇到的网站测试下效果。
我这没有案例，好奇fuzz的算法有没有效。

**Comment by mrknow001** [comment]
-z功能可以优化下，404状态fuzz，指定状态码fuzz，全局fuzz。因为程序员命名都有习惯，比如http://xxxx/file/images/upload，https://xxxx/file/upload

**Comment by mrknow001** [comment]
还有就是规则方面优化需要大幅加强，很多匹配不到

**Comment by mrknow001** [comment]
深入抓取不大理解，深入抓取是当前连接访问后获取的连接去抓取还是浏览器爬虫抓取。如果不是浏览器爬虫抓取，建议增加crawlergo联动爬虫抓取，将所有接口一网打尽

**Comment by pingc0y** [comment]
目前的fuzz是针对路径拼接错误的一个处理方式，不是对未知的路径去fuzz碰撞。这种也不适合黑盒的使用，如果抓出来一堆静态页面，程序还对他去进行接口的fuzz这显然不合适。这方面还是使用者自己提取需要的部分使用其他工具fuzz比较好。

目前的fuzz规则是提取所有主域名抓到的目录然后拆分凭拼接，拼接出来的数量是很可观的，用于碰撞正确路径的这些规则应该是足够的。

深入抓取就是针对html抓到的链接，深入一层继续抓取，多抓几层的话就很容易偏到其他站点去了。

crawlergo我测试爬取的链接貌似也不全。

要实现对着官网跑一下就抓到全部链接有点困难，我还是希望直接输入敏感页面，然后工具去小范围尽可能的抓取接口链接。
