### ISSUE TITLE
Release Mac OSX M1/M2 (arm64) 

### ISSUE THREAD

**Issue by secfb** [pingc0y/URLFinder#29]
The tool you wrote is really good. Can you share the mac osx(arm64) release version of this tool?

**Comment by pingc0y** [comment]
Has been released for all platforms, including arm64(URLFinder-macos64)

**Comment by sqws651515** [comment]
The execution command prompt of macos m1 is as follows：
```
xxx@xxxdeMBP URLFinder % URLFinder-macos64
zsh: command not found: URLFinder-macos64
```
<img width="443" alt="image" src="https://user-images.githubusercontent.com/101343301/195588094-d5ffb450-af6f-4229-85d9-afcf4e9d2da8.png">

**Comment by pingc0y** [comment]
> The execution command prompt of macos m1 is as follows：
> 
> ```
> xxx@xxxdeMBP URLFinder % URLFinder-macos64
> zsh: command not found: URLFinder-macos64
> ```
> 
> <img alt="image" width="443" src="https://user-images.githubusercontent.com/101343301/195588094-d5ffb450-af6f-4229-85d9-afcf4e9d2da8.png">

Sorry I don't have a macos environment, if it doesn't work you can compile it yourself on macos

**Comment by pingc0y** [comment]
I think I know, I will release a package for arm64

**Comment by secfb** [comment]
thank you.
