### ISSUE TITLE
不合适啊

### ISSUE THREAD

**Issue by gusechuisheng** [pingc0y/URLFinder#3]
![Snipaste_2022-06-15_17-30-56](https://user-images.githubusercontent.com/49669724/173795034-1d8a7e78-947b-4185-a553-134f2ce52677.png)
![Snipaste_2022-06-15_17-32-10](https://user-images.githubusercontent.com/49669724/173795070-d613b352-ea7a-4e7c-b3f8-b539b6a286c5.png)
看不懂，明明有这个找不到jsfinder能找到，而且输出都有问题

**Comment by pingc0y** [comment]
> ![Snipaste_2022-06-15_17-30-56](https://user-images.githubusercontent.com/49669724/173795034-1d8a7e78-947b-4185-a553-134f2ce52677.png) ![Snipaste_2022-06-15_17-32-10](https://user-images.githubusercontent.com/49669724/173795070-d613b352-ea7a-4e7c-b3f8-b539b6a286c5.png)看不懂,明明有这个找不到jsfinder能找到,而且输出都有问题

感谢反馈，已经对提取规则进行优化，增强了兼容性。请下载新版本测试
![1655347955058](https://user-images.githubusercontent.com/106963235/173981122-c5511c87-0574-4abb-83f6-174bce81b339.png)
