### ISSUE TITLE
建议添加js目录爆破js文件名功能，通过-参数指定，常见的一些就行

### ISSUE THREAD

**Issue by woshicym** [pingc0y/URLFinder#38]
js文件名，不是jquery框架的，config.js  app.js  main.js这些，或者自己指定字典

**Comment by pingc0y** [comment]
会考虑添加该功能，指定字典的话应该不会给单独参数，而是通过 -i 参数 配置文件中设置字典路径

**Comment by pingc0y** [comment]
添加了默认简单的js爆破
