### ISSUE TITLE
奇怪的报错

### ISSUE THREAD

**Issue by nf592** [pingc0y/URLFinder#39]
跑起来直接输出
os.(*File).Write(0xc00000a018, {0xc000469940?, 0xc, 0xc00021ff70?})
        D:/Go/src/os/file.go:175 +0x65
fmt.Fprintf({0x139d080, 0xc00000a018}, {0x130e25f, 0xa}, {0xc00021ff70, 0x1, 0x1})
        D:/Go/src/fmt/print.go:205 +0x9b
fmt.Printf(...)
        D:/Go/src/fmt/print.go:213
main.spider({0xc000027180, 0x91}, 0xf0?)
        D:/URLFinder/src/crawler.go:29 +0xac
created by main.jsFind
        D:/URLFinder/src/crawler.go:176 +0x4ee

goroutine 7275 [semacquire]:
internal/poll.runtime_Semacquire(0x12ba560?)
        D:/Go/src/runtime/sema.go:67 +0x25
internal/poll.(*fdMutex).rwlock(0xc000004500, 0xc0?)
        D:/Go/src/internal/poll/fd_mutex.go:154 +0xd2
internal/poll.(*FD).writeLock(...)
        D:/Go/src/internal/poll/fd_mutex.go:239
internal/poll.(*FD).Write(0xc000004500, {0xc00055cb50, 0xc, 0x10})
        D:/Go/src/internal/poll/fd_windows.go:656 +0x6c
os.(*File).write(...)
        D:/Go/src/os/file_posix.go:48
os.(*File).Write(0xc00000a018, {0xc00055cb50?, 0xc, 0xc000c65f70?})
        D:/Go/src/os/file.go:175 +0x65
fmt.Fprintf({0x139d080, 0xc00000a018}, {0x130e25f, 0xa}, {0xc000c65f70, 0x1, 0x1})
        D:/Go/src/fmt/print.go:205 +0x9b
fmt.Printf(...)
        D:/Go/src/fmt/print.go:213
main.spider({0xc0042e3730, 0x69}, 0x0?)
        D:/URLFinder/src/crawler.go:29 +0xac
created by main.jsFind
        D:/URLFinder/src/crawler.go:176 +0x4ee

goroutine 7233 [semacquire]:
internal/poll.runtime_Semacquire(0x12ba560?)
        D:/Go/src/runtime/sema.go:67 +0x25
internal/poll.(*fdMutex).rwlock(0xc000004500, 0xd0?)
        D:/Go/src/internal/poll/fd_mutex.go:154 +0xd2
internal/poll.(*FD).writeLock(...)
        D:/Go/src/internal/poll/fd_mutex.go:239
internal/poll.(*FD).Write(0xc000004500, {0xc0001889e0, 0xc, 0x10})
        D:/Go/src/internal/poll/fd_windows.go:656 +0x6c
os.(*File).write(...)
        D:/Go/src/os/file_posix.go:48
os.(*File).Write(0xc00000a018, {0xc0001889e0?, 0xc, 0xc00825ff70?})
        D:/Go/src/os/file.go:175 +0x65
fmt.Fprintf({0x139d080, 0xc00000a018}, {0x130e25f, 0xa}, {0xc00825ff70, 0x1, 0x1})
        D:/Go/src/fmt/print.go:205 +0x9b
fmt.Printf(...)
        D:/Go/src/fmt/print.go:213
main.spider({0xc003117ef0, 0x89}, 0xd0?)
        D:/URLFinder/src/crawler.go:29 +0xac
created by main.jsFind
        D:/URLFinder/src/crawler.go:176 +0x4ee

goroutine 7313 [runnable]:
main.jsFind.func4()
        D:/URLFinder/src/crawler.go:176
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1594 +0x1
created by main.jsFind
        D:/URLFinder/src/crawler.go:176 +0x4ee

**Comment by pingc0y** [comment]
师傅是跑的源代码吗，试试看下载的成品有没有报错

**Comment by nf592** [comment]
是使用师傅编译好的exe

**Comment by pingc0y** [comment]
这个报错我看不出来啥，方便的话提供下运行参数和url链接，我看看能不能复现

**Comment by nf592** [comment]
不好意思师傅，这边目前不能提供url，是公网发布前的测试，参数为 urlfind.exe -s all -m 2 -u host

**Comment by nf592** [comment]
师傅你可以本地搭建环境[minio](https://github.com/minio/minio)安装进行复现，直接-u xxx/login即可

**Comment by pingc0y** [comment]
> 师傅你可以本地搭建环境[minio](https://github.com/minio/minio)安装进行复现，直接-u xxx/login即可

下次更新修复

**Comment by pingc0y** [comment]
已更新

**Comment by nf592** [comment]
师傅YYDS
