### ISSUE TITLE
mac x86_64架构可执行文件报错 是不是编译出问题了

### ISSUE THREAD

**Issue by catw0rld** [pingc0y/URLFinder#40]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/68625234/215422274-5e957a46-41a3-4bbd-b646-4fe3decbc7e2.png">
<img width="402" alt="image" src="https://user-images.githubusercontent.com/68625234/215422301-8b29bb85-6495-461f-ac7d-843a5af7114d.png">

**Comment by catw0rld** [comment]
已解决

**Comment by G0rdita** [comment]
我也是这个问题，请问怎么解决的

**Comment by G0rdita** [comment]
已解决，自己编译下就可以了
