### ISSUE TITLE
建议：程序默认ua建议由爬虫ua替换为正常web浏览器ua

### ISSUE THREAD

**Issue by Sexisnull** [pingc0y/URLFinder#42]
昨天在使用时发现一个站明明可以访问，但是无法爬取js等信息，调试了下发现是内置ua的问题，一些网站会屏蔽爬虫，所以建议替换掉，一般情况下比较懒，不喜欢多增加一个参数去定制请求。
<img width="758" alt="image" src="https://user-images.githubusercontent.com/38177084/215637159-3e9d9a1c-c01a-4055-b11a-2253b641397f.png">

**Comment by Sexisnull** [comment]
随机ua也可以，类似如下
https://github.com/evilsocket/dirsearch/blob/master/uas.go

**Comment by pingc0y** [comment]
好的，下次更新改为随机ua
