### ISSUE TITLE
添加黑域名功能

### ISSUE THREAD

**Issue by i11us0ry** [pingc0y/URLFinder#43]
配置文件中添加一个数组，该数组中域名相关的url都不会爬取，不然每次爬取都会有aliyun、taobao等一大堆没必要的url或js，很浪费资源

**Comment by lapalipi** [comment]
最好是支持正则，去掉一堆没意义的站。

**Comment by pingc0y** [comment]
这个功能有实现，但是写死在代码里的，下个版本，黑名单、抓取规则等全部开放到yml配置文件里，可以自定义

**Comment by pingc0y** [comment]
已更新
