### ISSUE TITLE
macOS release binary is elf file

### ISSUE THREAD

**Issue by Arrnitage** [pingc0y/URLFinder#45]
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/48816467/218911413-668f2da3-3482-4b34-b4d0-b95a7e50b5f3.png">

**Comment by pingc0y** [comment]
感谢反馈，我重新打包检查了下，现在没有问题了。[https://github.com/pingc0y/URLFinder/releases/download/2023.2.3/URLFinder-macos-amd64.zip](url)

**Comment by Arrnitage** [comment]
> 感谢反馈，我重新打包检查了下，现在没有问题了。[https://github.com/pingc0y/URLFinder/releases/download/2023.2.3/URLFinder-macos-amd64.zip](url)

thx
