### ISSUE TITLE
过滤问题

### ISSUE THREAD

**Issue by lsadaharu** [pingc0y/URLFinder#46]
![微信图片_20230215114752](https://user-images.githubusercontent.com/50976099/218924530-62d7d65d-7a8a-4be2-9277-d367a731d433.png)
师傅，这里过滤的正则写错了吧

**Comment by lsadaharu** [comment]
windows不会自动生成config.yaml吗？

**Comment by pingc0y** [comment]
是的我也发现了，下次更新改正。windows下也会自动生成配置文件的

**Comment by lsadaharu** [comment]
哦哦，懂了，是要加-u参数再-i才会自动生成啊^^
