### ISSUE TITLE
-x没有效果，无法代理

### ISSUE THREAD

**Issue by cl0versec** [pingc0y/URLFinder#47]
<img width="755" alt="image" src="https://user-images.githubusercontent.com/61461657/220022605-6a19a7e7-ec62-4ba7-9d7c-59a7c2c70a19.png">

**Comment by pingc0y** [comment]
感谢反馈，下次更新修复该问题，可以暂时先使用 -i 配置文件来使用代理

**Comment by pingc0y** [comment]
已更新
