### ISSUE TITLE
建议添加多个主地址

### ISSUE THREAD

**Issue by Jrand-github** [pingc0y/URLFinder#5]
建议添加多个主地址

http://www.baidu.com/api
http://www.baidu.com/api-111

**Comment by yang-pingo** [comment]
> 建议添加多个主地址
> 
> http://www.baidu.com/api http://www.baidu.com/api-111

如果你是指抓取多个url的话，使用-f urls.txt 就可以了

urls.txt的内容：
http://www.baidu.com/api
http://www.baidu.com/api-111

**Comment by Jrand-github** [comment]
不是这个意思，就是拼接URL的时候，允许定义多个根路径 因为有一些js中的根路径不是domain 而是domain/api-hello/

**Comment by yang-pingo** [comment]
> 不是这个意思，就是拼接URL的时候，允许定义多个根路径 因为有一些js中的根路径不是domain 而是domain/api-hello/

可以提供下存在这个问题的url吗？你说的添加多个目录做JS前缀目录这个是不合理的，许多网站JS存在于各种不同的目录，人为的去干涉的话反而不合适。
