### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by YzaSoLong** [pingc0y/URLFinder#51]
我不知道怎么描述，这也许是我个人的问题：
当我需要使用URLFinder去爬取一个登录后的页面中的js时，出现加了-c选项加了 cookies 也无法访问到登录后页面的情况，于是我手动将页面中的js连接提取出来并放到文件里，然后URLFinder使用-f选项去解析这些js链接。然而虽然URLFinder跑出了这些js中的接口，但是这些是按照每个js链接来保存的，而由于这些js是同一个网站的js，并且js链接有十几个，这样就导致了结果很多重复，并且生成了三倍的结果文件。能否能多个去重的功能或者把结果放到同一个文件内的功能，例如指定 批量url为同一个网站，然后将结果视为一个url的结果来进行处理，这样FUZZ功能也能用的上。
不得不说，URLFinder是个非常好的工具。

**Comment by pingc0y** [comment]
添加了cookie也无法访问的话，可以尝试复制完整的请求头使用-i 参数 配置到配置文件里。
后面说的批量问题我会考虑这样处理：如果-f 里面的url都是同一个域名下的，那么抓取结果就视为一个url的结果来保存。
如果有更好的方式，欢迎师傅补充。

**Comment by YzaSoLong** [comment]
非常感谢你的回复。
我看到  -i 参数的描述为 ：-i  加载yaml配置文件（不存在时，会在当前目录创建一个默认yaml配置文件）  ，便以为是加载配置文件，而不是加载请求头。
也许能给-i 参数加上：加载请求头 的描述，这样可能会通俗易懂一点。
关于批量问题，也许可以给-f 加上额外的参数，例如 -f 1 便表示视为同一个url的结果，不加便表示依照url进行分割。这样便会多了一些选择余地（当然也有可能是更加复杂的使用文档.）。
