### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by hosolom** [pingc0y/URLFinder#54]
1. 在提取不到东西的时候还是会创建三个文件 csv,json,html  挺占用空间的。

`{"domain":[],"fuzz":null,"info":null,"js":null,"jsOther":null,"url":null,"urlOther":null}`

2. 默认运行不会创建配置文件,不生效
```  
-i    set configFile
        加载yaml配置文件（不存在时，会在当前目录创建一个默认yaml配置文件）
```

系统：ubuntu  22.04
版本：直接下载的Releases最新版文件

**Comment by pingc0y** [comment]
会考虑对没有获取到数据的情况做下处理
配置文件不是默认就会生成的，需要使用-i 参数才会生成默认yaml配置文件

**Comment by hosolom** [comment]
使用-i 也是没生成呢

**Comment by pingc0y** [comment]
确保有权限创建文件，可以截图给我看加-i参数后的提示信息

**Comment by pingc0y** [comment]
还有就是 -u -i 或者-f -i，不能单独-i

**Comment by hosolom** [comment]
当时用的./URLFinder-linux-amd64 -s all -m 2 -f url.txt -o out/  没生成
没有获取到数据的情况做下处理挺重要的，太多空文件干扰处理

**Comment by pingc0y** [comment]
./URLFinder-linux-amd64 -s all -m 2 -f url.txt -o out/ -i 

> 当使用的./URLFinder-linux-amd64 -s all -m 2 -f url.txt -o out/ 没有生成 没有获取到数据的情况做下处理坚持重要的，太多空间文件干修复
