### ISSUE TITLE
可以添加一个自定义路径吗 -o 只能本地生成文件

### ISSUE THREAD

**Issue by LiAoRJ** [pingc0y/URLFinder#7]
希望能适配 自定义路径 以及生成CSV 后缀文件
可参考此项目 https://github.com/msfisgood/JSFinderAAA

**Comment by pingc0y** [comment]
采纳了，下次更新加上：
	1.自定义文件目录
	2.生成文件改为csv后缀，表格查看更方便

**Comment by pingc0y** [comment]
已更新
