### ISSUE TITLE
希望增加探测深度选项，平衡目前的输出结果

### ISSUE THREAD

**Issue by ttstormxx** [pingc0y/URLFinder#72]
老版本：2022.07.06
当前版本：2023.05.11

问题：
1.当前版本的模式中m 1探测的结果太少，m 2和3的探测结果类别过多，且探测结果输出的内容非常多，绝大多数情况下不具有特别大的帮助，老版本的m 1中探测结果个人认为非常合适（仅包含JS链接和接口链接）
2.老版本可以通过管道符连接其他工具例如httpx，新版本因为添加了颜色输出导致无法配合其他工具

建议：
1. 添加平衡的m参数值，采取一个中间值，仅输出接口链接
2. 添加静默参数，仅输出链接以支持管道符

最后
大佬的工具非常赞，一开始就在使用，大大的解决了接口探测方面的流程问题。

**Comment by pingc0y** [comment]
m的深度 新版本是可以通过 -i 来配置的
仅输出接口链接的话，因为没办法准确判断这个url是接口还是页面，所以不好实现
静默参数的可以考虑加一个，只输出url不输出其他信息

**Comment by pingc0y** [comment]
没有加入静默，但改为-s参数的时候，链接去掉了颜色
