### ISSUE TITLE
wsl下一定概率首次无结果，win10正常

### ISSUE THREAD

**Issue by 0x0004** [pingc0y/URLFinder#75]
win10 wsl kali下首次对某网站执行后显示1spider后ok就未获取到数据，就结束了

**Comment by pingc0y** [comment]
这是请求没有获取到数据
1，对方网站有防火墙或反爬虫，可以通过配置一些参数来尝试绕过。
2，看下是不是电脑有开启代理，代理导致的请求获取失败。
