### ISSUE TITLE
直接./urlFinder -m 3 -s 200,500,302 -u  baidu.com 无法访问到数据 必须要加上http或https 才能访问

### ISSUE THREAD

**Issue by uumini** [pingc0y/URLFinder#80]
![image](https://github.com/pingc0y/URLFinder/assets/113664742/f857267b-a74f-4d91-8ef6-e1e7710e2471)
感觉有点呆，作者大大能改一下嘛

**Comment by uumini** [comment]
而且加上https 获取的数据 明显要比http 获取的多
![image](https://github.com/pingc0y/URLFinder/assets/113664742/8d380360-9f8e-4543-b572-8e25999b8a2d)

**Comment by pingc0y** [comment]
收到，下个版本支持

**Comment by pingc0y** [comment]
已更新支持
