### ISSUE TITLE
结果导出文件夹命名问题

### ISSUE THREAD

**Issue by yq1ng** [pingc0y/URLFinder#81]
命令：`.\URLFinder -u http://127.0.0.1:8880/ -m 3 -s all -z 1 -o . -i .\config.yaml`
导出文件夹/文件名为：`127.0.0.1：8880` 
期望导出名：`127.0.0.1:8880`
![image](https://github.com/pingc0y/URLFinder/assets/54146883/07fe6359-6d63-4bcb-bdaa-cec243ec87ce)
![image](https://github.com/pingc0y/URLFinder/assets/54146883/eb9e6770-f623-493c-a498-395dfcc1ce79)

**Comment by yq1ng** [comment]
师傅考虑支持导出自定义文件名吗，或者仅导出json
比如 -o xxx.json

**Comment by pingc0y** [comment]
windows环境不允许:作为文件名，为了统一所以就用了中文的：。自定义文件名和仅导出一种格式，后续更新会考虑支持

**Comment by pingc0y** [comment]
> 师傅考虑支持导出自定义文件名吗，或者仅仅导出json 比如-o xxx.json

现在支持导出指定类型
