### ISSUE TITLE
config.yaml里的User-Agent不生效,Accept会出现两个

### ISSUE THREAD

**Issue by cr1bug** [pingc0y/URLFinder#82]
![image](https://github.com/pingc0y/URLFinder/assets/54324046/f2d868d8-11fb-4f7e-97bc-8ee38536c4ba)
![image](https://github.com/pingc0y/URLFinder/assets/54324046/06c3e9eb-cbeb-4ea9-b66b-56ad17851ed1)

**Comment by pingc0y** [comment]
已更新修复
