### ISSUE TITLE
当js或url以./开头时,提取不到

### ISSUE THREAD

**Issue by cr1bug** [pingc0y/URLFinder#83]
![image](https://github.com/pingc0y/URLFinder/assets/54324046/bea4c49f-a375-4bd5-840c-19fb3ba3ab88)

**Comment by pingc0y** [comment]
是能提取到的[](url)
![1693560994125](https://github.com/pingc0y/URLFinder/assets/106963235/9f213d80-8b3e-4fd4-b8b6-d0a91ac3ec37)
![1693561008022](https://github.com/pingc0y/URLFinder/assets/106963235/b7d41d8f-c75e-4fd5-a8d2-797acd4dc271)

**Comment by cr1bug** [comment]
把href换成src试试

**Comment by cr1bug** [comment]
师傅试一下这个url
https://wx.17u.cn/ordercenterfront/

**Comment by pingc0y** [comment]
确实有这个bug，之前一次更新加的代码导致的，等下更新修复下
