### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by jinzezhi** [pingc0y/URLFinder#98]
<img width="1822" alt="image" src="https://github.com/pingc0y/URLFinder/assets/93123422/369a73cb-a9fc-40c3-a9c6-66198defdffc">
不会对新拼接到的地址再爬了嘛 和jsfinder 测试了下

**Comment by pingc0y** [comment]
你看js大小显示0，我试了下浏览器加载这个js花了1分半，是请求超时了就没获取到js里的地址

**Comment by jinzezhi** [comment]
okok 明白了
